// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKvAFMyXLKyruQu6sDGRT5s3cMyEZV8Gk',
    appId: '1:635527382106:web:c87c1d39be7b952aef4463',
    messagingSenderId: '635527382106',
    projectId: 'myquiz-74766',
    authDomain: 'myquiz-74766.firebaseapp.com',
    storageBucket: 'myquiz-74766.appspot.com',
    measurementId: 'G-6ZSBE6KWHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw6mbbWpxyxZ7UYZyuPAAKWQ8c4m76hNw',
    appId: '1:635527382106:android:f2e4d9adfd5be803ef4463',
    messagingSenderId: '635527382106',
    projectId: 'myquiz-74766',
    storageBucket: 'myquiz-74766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXlVLoTKbwgW8lM0-uvf-0Aviae5eLWG0',
    appId: '1:635527382106:ios:c711859f0fc84d0aef4463',
    messagingSenderId: '635527382106',
    projectId: 'myquiz-74766',
    storageBucket: 'myquiz-74766.appspot.com',
    iosClientId: '635527382106-bflacla30u9f4tivhknfabssqapdbh9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzledemo',
  );
}
